// Generated by the FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
///     await Firebase.initializeApp(
///       options: DefaultFirebaseOptions.currentPlatform,
///     );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // Estes são os valores corretos para a vossa plataforma Web,
      // copiados da vossa consola do Firebase.
      return const FirebaseOptions(
        apiKey: "AIzaSyDF2qdqOBav6_32TAHP3FSrLpvYPKuAbH8",
        appId: "1:487385761751:web:6ea724b68f5867d4ceed92",
        messagingSenderId: "487385761751",
        projectId: "hellofarmerapp-76626",
        authDomain: "hellofarmerapp-76626.firebaseapp.com",
        storageBucket: "hellofarmerapp-76626.firebasestorage.app",
      );
    }

    // A configuração para Android deve ser verificada no ficheiro google-services.json
    // mas por agora usamos valores semelhantes aos da web.
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return const FirebaseOptions(
          apiKey: "AIzaSyDF2qdqOBav6_32TAHP3FSrLpvYPKuAbH8", // Verifiquem este valor no google-services.json
          appId: "1:487385761751:android:54bb1ce6326e1a35ceed92", // Este é um exemplo, verifiquem no google-services.json
          messagingSenderId: "487385761751",
          projectId: "hellofarmerapp-76626",
          storageBucket: "hellofarmerapp-76626.firebasestorage.app",
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios.',
        );
      case TargetPlatform.macOS:
         return const FirebaseOptions(
          apiKey: "AIzaSyDF2qdqOBav6_32TAHP3FSrLpvYPKuAbH8",
          appId: "1:487385761751:web:6ea724b68f5867d4ceed92", // Usando web como fallback
          messagingSenderId: "487385761751",
          projectId: "hellofarmerapp-76626",
          authDomain: "hellofarmerapp-76626.firebaseapp.com",
          storageBucket: "hellofarmerapp-76626.firebasestorage.app",
        );
      case TargetPlatform.windows:
         return const FirebaseOptions(
          apiKey: "AIzaSyDF2qdqOBav6_32TAHP3FSrLpvYPKuAbH8",
          appId: "1:487385761751:web:6ea724b68f5867d4ceed92", // Usando web como fallback
          messagingSenderId: "487385761751",
          projectId: "hellofarmerapp-76626",
          authDomain: "hellofarmerapp-76626.firebaseapp.com",
          storageBucket: "hellofarmerapp-76626.firebasestorage.app",
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }
}
